apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in
      scale:
        min: 2
      containerTemplate:
#        env:
#          - name: NUMAFLOW_DEBUG
#            value: "true"
        resources:
          limits:
            cpu: 3000m
            memory: 6Gi
          requests:
            cpu: 1000m
            memory: 4Gi
      source:
        # A self data generating source
        generator:
          rpu: 3000
          duration: 1s
          msgSize: 1024
    - name: cat
      scale:
        min: 2
      udf:
        builtin:
          name: cat # A built-in UDF which simply cats the message
    - name: out
      scale:
        min: 2
      sink:
        # A simple log printing sink
        blackhole: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out
