apiVersion: numaflow.numaproj.io/v1alpha1
kind: InterStepBufferService
metadata:
  name: default
spec:
  jetstream:
    version: latest
    replicas: 3
#    containerTemplate:
#      resources:
#        limits:
#          memory: 10Gi
#        requests:
#          cpu: 1
#          memory: 8Gi
    persistence:
      accessMode: ReadWriteOnce
      volumeSize: 50Gi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: isbsvc
                  numaflow.numaproj.io/isbsvc-name: default
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
#    bufferConfig: |
#      stream:
#        retention: 0
#        maxMsgs: 100000