apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: reduce-sliding-pipeline
spec:
  vertices:
    - name: in
      scale:
        min: 1
        max: 1
      containerTemplate:
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 1Gi
      source:
        # A self data generating source
        generator:
          rpu: 100
          duration: 1s
#          msgSize: 256
    - name: fixed
      udf:
        container:
          image: quay.io/numaio/numaflow-go/reduce-counter
        groupBy:
          window:
            fixed:
              length: 10s
          keyed: true
          storage:
            persistentVolumeClaim:
              volumeSize: 5Gi
              accessMode: ReadWriteOnce
      containerTemplate:
        env:
          - name: NUMAFLOW_PPROF
            value: "true" # DO NOT forget the double quotes!!!
    - name: sink
      scale:
        min: 1
        max: 1
      sink:
        log: {}
  edges:
    - from: in
      to: fixed
      parallelism: 3
    - from: fixed
      to: sink