apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  limits:
    readBatchSize: 1000
    bufferMaxLength: 50000
    bufferUsageLimit: 85
  vertices:
    - name: in
      scale:
        min: 5
      containerTemplate:
#        env:
#          - name: NUMAFLOW_DEBUG
#            value: "true"
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 2Gi
      source:
        # A self data generating source
        generator:
          rpu: 6000
          duration: 1s
          msgSize: 1024
    - name: out
      scale:
        min: 6
      sink:
        blackhole: {}
  edges:
    - from: in
      to: out
