apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: even-odd
spec:
  vertices:
    - name: in
      source:
        http: {}
    - name: even-or-odd
      scale:
        min: 1
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true"
      udf:
        container:
          # Tell the input number is even or odd, see https://github.com/numaproj/numaflow-go/tree/main/pkg/function/examples/even_odd
          image: quay.io/numaio/numaflow-go/map-even-odd
    - name: even-cat
      scale:
        min: 1
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true"
      udf:
        builtin:
          name: cat # A built-in UDF which simply cats the message
    - name: odd-cat
      scale:
        min: 1
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true"
      udf:
        builtin:
          name: cat # A built-in UDF which simply cats the message
    - name: even-sink
      scale:
        min: 1
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true"
      sink:
        # A simple log printing sink
        log: {}
    - name: odd-sink
      scale:
        min: 1
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true"
      sink:
        log: {}
  edges:
    - from: in
      to: even-or-odd
    - from: even-or-odd
      to: even-cat
      conditions:
        keyIn:
          - even
    - from: even-or-odd
      to: odd-cat
      conditions:
        keyIn:
          - odd
    - from: even-cat
      to: even-sink
    - from: odd-cat
      to: odd-sink
